// model:
// input.gaji_pegawai_id
// input.gaji_bulan
// input.gaji_pokok
// input.gaji_jasa
// input.gaji_honor
// input.gaji_insentif
// input.gaji_tunj_jabatan
// input.gaji_tunj_beras
// input.gaji_kesra
// input.gaji_pot_kesra
// input.gaji_pot_pulsa
// input.gaji_bersih