// model:
// input.pegawai_nik
// input.pegawai_anggota_id
// input.pegawai_nama
// input.pegawai_lahir_date
// input.pegawai_lahir_tempat
// input.pegawai_telp
// input.pegawai_npwp_no
// input.pegawai_no_identitas
// input.pegawai_pend_jenjang
// input.pegawai_pend_jurusan
// input.pegawai_pend_thn_lulus
// input.pegawai_almt_ktp
// input.pegawai_almt_domisili
// input.pegawai_penyertaan
// input.pegawai_gajipokok
// input.pegawai_tunj_jabatan
// input.pegawai_kesra
// input.pegawai_tunj_beras
// input.pegawai_masuk_date